start python solver_worker.py accentuation
start python solver_worker.py a+b
start python solver_worker.py colors
start python solver_worker.py I-love-time
start python solver_worker.py I-love-time
start python solver_worker.py I-love-time
start python solver_worker.py poems
start python solver_worker.py s-like-$
start python solver_worker.py tts
start python solver_worker.py tts
start python solver_worker.py tts
start python solver_worker.py tsya
